[package]
name = "hr"
version = "1.0.0"
authors = ["Matthew Gamble <git@matthewgamble.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_size = "0.3.2"
